import time
import threading
import json
from collections import deque
from http.server import BaseHTTPRequestHandler, HTTPServer
from opentelemetry.sdk._logs import LogRecordProcessor

class RecentLogCounterProcessor(LogRecordProcessor):
    def __init__(self, window_seconds=30):
        self.window_seconds = window_seconds
        self._lock = threading.Lock()
        # Stores tuples of: (timestamp_in_seconds, is_warning, is_error)
        self._recent_logs = deque()

    def emit(self, log_data):
        """Intercepts logs as they are generated by the application."""
        record = log_data.log_record
        
        # OTel stores timestamps in nanoseconds, fallback to current time
        ts = record.timestamp / 1e9 if record.timestamp else time.time()
        
        # OTel SeverityNumbers: 
        # 1-8: TRACE/DEBUG, 9-12: INFO, 13-16: WARN, 17-24: ERROR/FATAL
        sev = record.severity_number
        is_warn = sev is not None and 13 <= sev.value <= 16
        is_error = sev is not None and sev.value >= 17

        with self._lock:
            self._recent_logs.append((ts, is_warn, is_error))

    def get_last_30s_stats(self):
        """The function that returns the requested metrics for application logs."""
        current_time = time.time()
        cutoff_time = current_time - self.window_seconds

        with self._lock:
            # Eject logs older than 30 seconds
            while self._recent_logs and self._recent_logs[0][0] < cutoff_time:
                self._recent_logs.popleft()

            total = len(self._recent_logs)
            warnings = sum(1 for log in self._recent_logs if log[1])
            errors = sum(1 for log in self._recent_logs if log[2])

        return {
            "total_logs": total,
            "warnings": warnings,
            "errors": errors
        }

    def shutdown(self):
        pass

    def force_flush(self, timeout_millis=30000):
        return True


class OTLPSystemLogHandler(BaseHTTPRequestHandler):
    """
    HTTP Handler to receive OTLP JSON logs from the OpenTelemetry Collector.
    This acts as a platform-agnostic receiver for all computer logs.
    """
    def do_POST(self):
        if self.path == '/v1/logs':
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length)
            
            try:
                payload = json.loads(post_data.decode('utf-8'))
                self.server.system_log_counter._process_otlp_payload(payload)
                
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(b'{}')
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                print(f"Error processing OTLP logs: {e}")
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, format, *args):
        # Suppress default HTTP logging to avoid spam
        pass


class SystemLogCounter:
    """
    Sets up a local OTLP HTTP receiver to collect system logs
    forwarded by the OpenTelemetry Collector. This is the platform-agnostic
    way to receive all logs of the computer (Windows Event Logs, syslog, macOS logs, etc.).
    """
    def __init__(self, window_seconds=30, host='127.0.0.1', port=4318):
        self.window_seconds = window_seconds
        self.host = host
        self.port = port
        self._lock = threading.Lock()
        self._recent_logs = deque()
        self._server = None
        self._thread = None

    def start(self):
        self._server = HTTPServer((self.host, self.port), OTLPSystemLogHandler)
        self._server.system_log_counter = self
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()

    def stop(self):
        if self._server:
            self._server.shutdown()
            self._server.server_close()
            self._thread.join()

    def _process_otlp_payload(self, payload):
        current_time = time.time()
        
        with self._lock:
            # Parse OTLP LogsData format
            resource_logs = payload.get('resourceLogs', [])
            for r_log in resource_logs:
                scope_logs = r_log.get('scopeLogs', [])
                for s_log in scope_logs:
                    log_records = s_log.get('logRecords', [])
                    for record in log_records:
                        # SeverityNumbers: 13-16 WARN, 17-24 ERROR/FATAL
                        sev = record.get('severityNumber', 0)
                        is_warn = 13 <= sev <= 16
                        is_error = sev >= 17
                        
                        ts_nano = record.get('timeUnixNano')
                        if ts_nano:
                            ts = int(ts_nano) / 1e9
                        else:
                            ts = current_time
                            
                        self._recent_logs.append((ts, is_warn, is_error))

    def get_last_30s_stats(self):
        """Returns the number of computer logs, warnings, and errors in the last 30s."""
        current_time = time.time()
        cutoff_time = current_time - self.window_seconds

        with self._lock:
            # Eject logs older than 30 seconds
            while self._recent_logs and self._recent_logs[0][0] < cutoff_time:
                self._recent_logs.popleft()

            total = len(self._recent_logs)
            warnings = sum(1 for log in self._recent_logs if log[1])
            errors = sum(1 for log in self._recent_logs if log[2])

        return {
            "total_logs": total,
            "warnings": warnings,
            "errors": errors
        }